version: '2'

tasks:
  build:
    desc: Build executable
    preconditions:
      - which nim
    cmds:
      - nim c -o:nca src/nca.nim 

  release:
    desc: Build in release mode
    preconditions:
      - which nim
    cmds:
      - nim c -o:nca -d:danger -d:release --opt:size -d:shellNoDebugCommand --passC:-flto --passL:-flto src/nca.nim 
      - strip nca

  clean:
    desc: Clean up artifacts
    cmds:
      - rm nca
